# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

PROMETHEUS_VERSION = ENV.fetch('PROMETHEUS_VERSION', "2.26.0")

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"

  config.vm.provision "file", source: "./files/prometheus.yml", destination: "/tmp/prometheus.yml"
  config.vm.provision "file", source: "./files/prometheus.service", destination: "/tmp/prometheus.service"
  config.vm.provision "file", source: "./files/prometheus-datasource.yaml", destination: "/tmp/prometheus-datasource.yaml"

  config.vm.provision "shell", inline: <<-EOF
    # setup users
    sudo useradd --system -M --shell /bin/false prom
    sudo useradd --system -M --shell /bin/false grafana

    # prometheus
    ## prepare directories
    sudo mkdir -p /etc/prometheus /var/lib/prometheus

    ## download and install
    wget -nv -P /tmp https://github.com/prometheus/prometheus/releases/download/v#{PROMETHEUS_VERSION}/prometheus-#{PROMETHEUS_VERSION}.linux-amd64.tar.gz
    cd /tmp
    tar xzvf prometheus-#{PROMETHEUS_VERSION}.linux-amd64.tar.gz
    sudo mv prometheus-#{PROMETHEUS_VERSION}.linux-amd64/prom{etheus,tool} /usr/local/bin
    sudo cp -R prometheus-#{PROMETHEUS_VERSION}.linux-amd64/console{s,_libraries} /etc/prometheus
    sudo chown -R prom: /usr/local/bin/prom{etheus,tool} /etc/prometheus /var/lib/prometheus

    ## copy homegrown configs
    sudo mv /tmp/prometheus.yml /etc/prometheus/prometheus.yml
    sudo mv /tmp/prometheus.service /etc/systemd/system/prometheus.service

    ## enable and start the service
    sudo systemctl enable --now prometheus

    # grafana
    wget -nv -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
    echo "deb https://packages.grafana.com/enterprise/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
    echo "deb https://packages.grafana.com/enterprise/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
    sudo apt update
    sudo apt install -y grafana-enterprise

    sudo mv /tmp/prometheus-datasource.yaml /etc/grafana/provisioning/datasources/prometheus.yaml

    ## enable and start the service
    sudo systemctl enable --now grafana-server
  EOF

  config.vm.network "forwarded_port", guest: 3000, host: 3000
end
