global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node_exporter
    scrape_interval: 10s
    static_configs:
      - targets:
        - 192.168.50.100:9100
  - job_name: blackbox
    scrape_interval: 10s
    static_configs:
     - targets:
       - 192.168.50.100:22
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: localhost:9115
